
server.port=9090

spring.cloud.gateway.server.webmvc.routes[0].id=my-emp-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://EMP-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/employee/**

spring.cloud.gateway.server.webmvc.routes[1].id=my-dept-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://DEPT-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/department/**


